# Generated by Django 5.0.2 on 2024-02-27 13:50

import people.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=people.utils.get_photo_upload_path, verbose_name='Фото'),
        ),
    ]
